### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by Arex-rus** [RimWorld-zh/RimTrans#24]
I could not start this program. When the program starts, an error message takes off. I have Win7 SP1 x64 (Russian), .NET Framework is installed. I quote the message with problem signature, if you need it.

```
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	RimTrans.exe
  Problem Signature 02:	0.18.2.5
  Problem Signature 03:	5a2cf07e
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c0eac
  Problem Signature 07:	157f
  Problem Signature 08:	fc
  Problem Signature 09:	System.IO.DirectoryNotFound
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1049
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
```

**Comment by duduluu** [comment]
The log said that directory not found.
Did you get the whole files of the program?

**Comment by Arex-rus** [comment]
Of cause, I unpacked content of the downloaded archive into new directory. Now full path to executive file is `E:\Projects\L10n\Rimworld\RimTrans\RimTrans.exe`
[Screenshot](http://i2.imageban.ru/out/2017/12/28/aecd47d99ac9f287dc9a5737ebdd506b.png)

**Comment by Arex-rus** [comment]
I checked, the directory contains all files from the archive.

**Comment by duduluu** [comment]
Have a try to move the folder to other position?

**Comment by Arex-rus** [comment]
I tried to launch from folder `D:\RimTrans_0.18.2.5_Beta\`. The result is unchanged.

**Comment by duduluu** [comment]
I have search the problem on google.
It might be that you haven't install the corret .net runtime.
Are you sure that you have install the .net which is **4.6.1** version?

**Comment by Arex-rus** [comment]
I also have a surmise that it is not bag of the program, but bug of .NET installation or OS. There is no crushes on other computer with the same version of RimTrans, .NET and OS.

**Comment by Monges** [comment]
I have that issue too.
 Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	RimTrans.exe
  Сигнатура проблемы 02:	0.18.2.6
  Сигнатура проблемы 03:	5b254847
  Сигнатура проблемы 04:	mscorlib
  Сигнатура проблемы 05:	4.6.1590.0
  Сигнатура проблемы 06:	5787ed44
  Сигнатура проблемы 07:	1587
  Сигнатура проблемы 08:	fc
  Сигнатура проблемы 09:	System.IO.DirectoryNotFound
  Версия ОС:	6.3.9600.2.0.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	5861
  Дополнительные сведения 2:	5861822e1919d7c014bbb064c64908b2
  Дополнительные сведения 3:	bb02
  Дополнительные сведения 4:	bb02c3b29c3f075104f1d0629e885cfc

**Comment by duduluu** [comment]
outdated
