### ISSUE TITLE
why are you distributing the RW source code with this tool?

### ISSUE THREAD

**Issue by FluffierThanThou** [RimWorld-zh/RimTrans#26]

**Comment by duduluu** [comment]
It's just for defs template generating.
https://github.com/RimWorld-zh/RimWorld-Defs-Templates
Is it violate the license?

**Comment by Karel-Kroeze** [comment]
Probably :P 

Wouldn't just including the dll - or telling users to copy their dll - be enough? 

Currently, you actually have the source code for most if not all of the game in there, which I'm 99% sure is violating something.

**Comment by duduluu** [comment]
Yes, the RimTrans core function actually dependency on the dll. The source code of RimWorld is just for getting default values on some def fileds, and has been removed from release.
